[package]
name = "digital-cr-logbook"
version = "1.0.0"
description = "27 CFR 478.125(f) Compliant Curios & Relics Collector Logbook"
authors = ["Weaver B."]
edition = "2021"

[lib]
name = "digital_cr_logbook_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
